collinbarrett/FilterLists

data/FilterList.json

Add 0131 Block List

---

data/FilterList.json
data/FilterListLanguage.json
data/FilterListMaintainer.json
data/Software.json
data/SoftwareSyntax.json

Added language tags to 2 lists, assigned more of gorhill's lists to gorhill, removed an incorrect E-mail address, and added one new list.

Some minor polishing

---

data/FilterList.json

doing some of the easier ones first pass

add some easy syntaxIDs

---

data/FilterList.json

Adding, I checked the data model.

added EasyList Brasil

---

data/Maintainer.json

Adding, I checked the data model.

Author EasyList Brasil

---

data/FilterListLanguage.json

Adding, I checked the data model.

Language for EasyList Brasil

---

data/FilterListMaintainer.json

maintainer EasyList Brasil

---

data/FilterList.json
data/FilterListTag.json

Update Polish Filterlists

---

data/FilterList.json

Fix viewUrl for KAD Whitelist

---

data/FilterList.json
data/FilterListLanguage.json
data/FilterListTag.json
data/Software.json
data/SoftwareSyntax.json

I **love** the new software dropdown system. So I decided to assign more syntaxes to the softwares in a hurry, e.g. domains for uBlock Origin, etc.
I've also found 12 new lists, most of them from Steven Black's source listings.

Tuesday daytime pull, incl. 12 new lists

---

data/License.json

Hoping to fix #466

---

data/FilterListTag.json

I decided to take care of assigning a fair few lists to the tags for ads, privacy and malware, basically.
Due to the large scope of the data (288 taggings) I had to handle, I didn't take care of sorting them properly into the existing tagging list, and I only partially ensured the absence of duplicate tags.

Saturday pull

---

data/FilterListTag.json
data/SoftwareSyntax.json

Sunday afternoon pull

---

data/FilterList.json
data/Software.json
data/SoftwareSyntax.json
data/Syntax.json

This pull aims to cover #307, #452, #453, #463, #473, #474, #475, #476 and #477.
My afternoon is however booked up, so I didn't have time to add tags and languages immediately.

Added 57 lists, 7 mirrors, and some other stuff

---

data/FilterList.json

Update Polish Filters

---

data/FilterList.json
data/FilterListLanguage.json
data/FilterListTag.json
data/Software.json
data/SoftwareSyntax.json

By now I'm surprising even myself with how many lists I've seemingly been able to dig up.

Tuesday night pull

---

data/FilterList.json
data/FilterListLanguage.json
data/FilterListTag.json

I had sat on most of these lists for a week's time while awaiting the outcome of #507, but since I was on a roll, I figured that I could just as well add them too.

Wednesday afternoon pull

---

data/FilterList.json
data/FilterListLanguage.json

I near-randomly decided to google `site:easylist-msie.adblockplus.org`, chose to show the "similar" search results, and struck a goldmine.

Found 28 more TPL lists

---

data/FilterList.json
data/FilterListTag.json
data/Maintainer.json

- - - - -
- Fix EasyList Thailand license data (Point to Apache 2.0)
- Add description for my (kowith337) lists
- Relocate my list locations
- Change my maintainer name to have full name

Little fix data (ELTH + Me)

---

src/FilterLists.Api/DependencyInjection/Extensions/IWebHostExtension.cs
src/FilterLists.Api/FilterLists.Api.csproj
src/FilterLists.Api/Program.cs
src/FilterLists.Api/Startup.cs
src/FilterLists.Data/Seed/Extensions/SeedFilterListsDbContext.cs

#540 use async seeding method in Main();

add async seeding in Main()

---

data/FilterList.json
data/FilterListTag.json

After I decided to relax for a few days, I've made this pull.

Monday afternoon pull

---

data/FilterList.json
data/FilterListTag.json
data/Tag.json

So my plan for today is to gradually sift through lists, by looking for clear patterns in tagless lists, giving those lists tags, waiting 90min for the API refresh, and then looking for new patterns.
And yes, I love that the refresh time is now 1-hour-ish instead of 4. 💙

Monday evening pull

---

data/FilterList.json
data/FilterListTag.json

And now, as far as I can see, every single list on FilterLists.com have been assigned at least one tag.

Monday night pull

---

data/FilterListTag.json

Okay, *this* time I believe that tags have been added to all lists. Second time's the charm.

Monday night pull, part 2

---

data/FilterList.json
data/FilterListLanguage.json
data/License.json

So now that licences have recently begun to be displayed more prominently on FilterLists.com, I guess that that's the next thing I'll be sifting through.

Tuesday morning pull

---

data/FilterList.json
data/FilterListLanguage.json
data/FilterListMaintainer.json
data/FilterListTag.json
data/Maintainer.json
data/Software.json
data/SoftwareSyntax.json

This pull also aims to resolve #560 and #561.

Thursday daytime pull

---

data/FilterList.json
data/FilterListMaintainer.json
data/FilterListTag.json
data/SoftwareSyntax.json

This pull is a small one, compared to most of the previous ones. It chiefly adds some details for the sake of uMatrix now that I've experienced a slight bit with it, and adds 1 additional list on top of that.

Friday afternoon pull

---

data/FilterList.json
data/FilterListLanguage.json
data/FilterListMaintainer.json
data/FilterListTag.json
data/Maintainer.json

It's mostly from my repos, but the last one is from another, however it's outdated but I'm still want to add into database.
- Facebook Zuckestion Killer
- Facebook Modules Command List
- All of adservice.google.com and id.google.com regional hosts
- Thai Paranoid Block `~Maximum~`
- sipp11's Thai Ad Filters

Attempt to add 5 lists

---

data/FilterList.json
data/FilterListMaintainer.json
data/FilterListTag.json

This pull only really takes care of adding the three new lists that I've made this afternoon.

Friday night pull

---

.travis.yml
FilterLists.sln
tests/FilterLists.Services.Tests/Extensions/AddIfNotNullOrEmptyShould.cs
tests/FilterLists.Services.Tests/FilterLists.Services.Tests.csproj

Add first unit test and run with Travis CI

---

data/FilterList.json
data/FilterListLanguage.json
data/FilterListTag.json

In addition to fixing #595, this pull also adds some mirrors that I had originally created with https://github.com/uBlockOrigin/uBlock-issues/issues/278 in mind, adds 3 new lists, assigned 4 lists to English, changed the tags of 2 lists, and possibly some other things too.

Wednesday early morning pull

---

data/FilterList.json

Correcting what I presume has been a build issue with #599.

Added missing comma

---

data/FilterList.json
data/FilterListLanguage.json
data/FilterListTag.json

Fixes https://github.com/collinbarrett/FilterLists/issues/604
Hopefully this is the correct way for list removal in this project.

Remove FIN-0 list due to breach of trust

---

data/FilterList.json
data/FilterListTag.json

Add https://gitlab.com/curben/urlhaus-filter

add URLhaus Malicious URL Blocklist

---

data/FilterList.json
data/FilterListMaintainer.json
data/FilterListTag.json

A small one, to add one list that I've made and one list that I've stumbled across.

Saturday night pull

---

data/FilterList.json

add mirror links to urlhaus filter

---

data/FilterList.json
data/FilterListLanguage.json
data/FilterListTag.json

Removed AdGuard Personal Block List

---

data/FilterList.json
data/FilterListLanguage.json
data/FilterListMaintainer.json
data/FilterListTag.json
data/Merge.json

deleted dead links

---

data/FilterList.json
data/FilterListMaintainer.json
data/FilterListTag.json

- Add 2 hosts from #616
- Update Mirror
- Re-Sort e6e46f6e01da1eeb6d271b0c7613b66084212954

For close #616

---

data/FilterList.json

remove some Notabug mirrors for #624

---

data/FilterList.json

I have no interest of doing it for ABP etc.

Crapblock Annoyances only with uBO/AdGuard

---

data/FilterList.json

Reverts collinbarrett/FilterLists#630
Set syntax id for correct list; Updated description for Block Google Fonts list

crapblock annoyance syntax id

---

data/FilterList.json
data/FilterListMaintainer.json
data/FilterListTag.json

I decided to be quite a bit productive tonight.
I'd understand it if *Twitter De-Politificator* was to raise some eyebrows, but as an ex-frequent-user of Twitter, and from Europe at that, I felt that Twitter took a sharp turn for the worse back in 2016 due to huge amounts of politics in general, and that this list is something that could bring Twitter back into the cosy coffee club state it was in back in 2015.

Thursday morning pull

---

data/FilterList.json
data/FilterListMaintainer.json
data/FilterListTag.json

https://github.com/collinbarrett/FilterLists/issues/666#issue-400958940 explains everything I needed to know in order to make this pull.
I also decided to take care of the one list that had previously been thought of as a fairly plausibly problematic list (Compare with https://ssl.bblck.me/blacklists/hosts-file.txt).

Resolving #666

---

data/FilterList.json
data/FilterListTag.json

added Web Annoyances Ultralist - CSS Style Modifying Filters

---

data/FilterList.json
data/FilterListLanguage.json
data/FilterListMaintainer.json
data/FilterListTag.json
data/Maintainer.json

fix #575
check @neoFelhz
fix #577
there is not a lot. Do you have any other information on StopForumSpam?
@collinbarrett @DandelionSprout

NeoHosts and StopForumSpam fix #575 #577

---

data/FilterList.json
data/FilterListMaintainer.json
data/FilterListTag.json

Add 4
- Facebook Zero Hosts Block (Test List)
- kowith337's Custome leftover hosts
- kowith337's Miscellaneous Annoyance
- iHateCircles
Edit 4
- Anti Survived Tracking Link Warning (Rewrite Description)
- Facebook Zero Hosts Block (Rewrite Description)
- [Change] Facebook Zero Hosts Block NoEdge > Facebook Zero Hosts Block Static
- CHEF-KOCH's Pinterest Hosts (Forgot to add "Pinterest" word in title)

Redone https://github.com/collinbarrett/FilterLists/pull/668

---

data/FilterList.json

I found this after I've copy something about myself to GitLab, few months ago, I guess.

Replace some mirrors of StevenBlack's lists

---

data/FilterList.json

fix #681
fixed with Shalla List Aggressive Urls in Shalla List Alcohol Urls

fix #681correcting a typo

---

data/FilterList.json

No idea if i've done it correctly, or managed to still do some mistakes.

Update SteamScamSite and adding the light version of it.

---

data/FilterList.json
data/FilterListLanguage.json
data/FilterListMaintainer.json
data/FilterListTag.json

At the expense of the last list, I am not sure about the correctness of the syntax choice ... I put 9, should I put 15?

4 lists: anudeepND facebook; Phishing Army; TR-PhishingList URL List; TR-PhishingList IP List

---

data/FilterList.json
data/FilterListLanguage.json
data/FilterListMaintainer.json
data/FilterListTag.json
data/Fork.json
data/Maintainer.json

@collinbarrett I have a question, that these links need to be deleted?
https://ransomwaretracker.abuse.ch/downloads/CW_PS_IPBL.txt
https://ransomwaretracker.abuse.ch/downloads/CW_PS_DOMBL.txt
https://raw.githubusercontent.com/eEIi0A5L/adblock_filter/master/beta.txt

404 Lists, again

---

data/FilterList.json
data/FilterListMaintainer.json
data/FilterListTag.json

This one is simply about adding my 2 newest lists, and changing some minor details of another list.

Mid-February pull

---

data/FilterList.json
data/FilterListMaintainer.json
data/FilterListTag.json

A small one this time, adding my newest list as well as 1 other list that I came across.

Early March pull

---

data/FilterList.json
data/FilterListMaintainer.json
data/FilterListTag.json
data/Maintainer.json

close #707 
@collinbarrett how to come up with a description?

Oppa chin choppa

---

data/FilterList.json
data/FilterListMaintainer.json
data/FilterListTag.json
data/Maintainer.json

@collinbarrett Found/updated/added information for `Maintainer.json`
`FilterListMaintainer.json` then I corrected the error (my), it turns out this person already have page (_in the previous update I added it again_), only the link had it not the main page of its website.
***
closes #719

again update?

---

data/FilterList.json
data/FilterListMaintainer.json
data/FilterListTag.json
data/Maintainer.json

closes #720
check me @kano1
if u have twitt account or email, i can write his in `Maintainer.json` it's not obligatory. but (probably) desirable

kano lists scrip

---

data/FilterList.json

License 4 = GPLv3
Syntax 3 = Adblock Plus
The GitHub web editor added the newline at the end. I hope it’s okay.

Add license and syntax of “Hello, Goodbye!” list

---

data/FilterList.json
data/FilterListMaintainer.json
data/FilterListTag.json

Changes
* 690 = 1488 and 690 is more complete so kept 690 (fixed the syntax id though)
* 692 = 1489 and 692 is more complete
* 1491 = 1492

Remove duplicate entries (same name, same viewUrl)

---

data/FilterList.json
data/FilterListMaintainer.json
data/FilterListTag.json
data/Maintainer.json
data/Tag.json

* Added my 3 newest lists.
* Changed "MVPS Hosts maintainer" to "Mike Burgess".
* Created 1 new tag, `userstyle`, and populated it with 5 lists.

Created my 50th adblock list! 🥳

---

data/FilterList.json
src/FilterLists.Web/ClientApp/modules/home/components/linkButtons/SubscribeButton.tsx

I'd be mightily surprised if I've actually written the code right, but still.

Attempting to make better subscription buttons for TPL and .onion lists

---

src/FilterLists.Web/ClientApp/modules/home/components/detailsExpander/infoCard/UpdatedDate.tsx
src/FilterLists.Web/ClientApp/modules/home/components/linkButtons/SubscribeButton.tsx
src/FilterLists.Web/ClientApp/site.css

Hoping to resolve most of the issues that were present in #744.

Polishing of UI changes

---

src/FilterLists.Web/ClientApp/modules/home/components/detailsExpander/infoCard/UpdatedDate.tsx

We're getting closer to something, I can feel it.

Date formatting, take 4

---

data/FilterList.json
data/FilterListMaintainer.json
data/FilterListTag.json
data/Maintainer.json

Adding a filter to hide game of thrones spoilers

add unsullied filter

---

.github/README.md
src/FilterLists.Web/Views/Shared/_Layout.cshtml

As per https://github.com/collinbarrett/FilterLists/issues/751#issuecomment-481381263.

Acknowledging that IE support is a goner

---

.travis.yml

Trying to fix Travis build being seen in #764 and #765 .

try bumping .NET SDK ver

---

data/FilterList.json
data/FilterListLanguage.json
data/FilterListMaintainer.json
data/FilterListTag.json
data/Maintainer.json

sync #764 w/upstream fix

---

data/FilterList.json
data/FilterListLanguage.json
data/FilterListMaintainer.json
data/FilterListTag.json

Adding hosts file

---

data/FilterList.json

Other description for lists

---

data/FilterList.json
data/FilterListLanguage.json
data/FilterListMaintainer.json
data/FilterListTag.json

* Added my 2 newest lists.
* Changed the syntaxId of *All-in-One Customized Adblock List*, as it uses many `:style` entries, which are nowadays known to cause heavy breakage in Adblock Plus.
* Switched 2 languageId-s around.
* Assigned *Web Annoyances Ultralist - CSS Style Modifying Filters* to yourduskquibbles.

Mid-May pull

---

data/FilterList.json
data/FilterListLanguage.json
data/FilterListTag.json
src/FilterLists.Web/ClientApp/modules/home/components/linkButtons/SubscribeButton.tsx

• Added 2 new lists.
• Did some maintenance of various Little Snitch-related stuff.

Mid-May pull 2

---

data/FilterList.json

I had forgot that I had made a small promise to intr0 to add his newest .onion links, after he requested help from me to add them in an E-mail.

Amendment to «Mid- or late-May pull»

---

data/FilterList.json
data/FilterListLanguage.json
data/FilterListMaintainer.json
data/FilterListTag.json

Almost solely thanks to the FilterLists Hub, I have become able to create tailorsewn and semi-synced versions of my Nordic list, so I figured I should add them to FilterLists.com in a hurry.

Hotfix for my two new list versions

---

data/FilterList.json
data/FilterListLanguage.json
data/FilterListMaintainer.json
data/FilterListTag.json
data/Merge.json

big cleaning

---

data/FilterList.json
data/FilterListLanguage.json
data/FilterListMaintainer.json
data/FilterListTag.json

Added my newest list, and changed the definition of one of my earlier lists.
Noteworthily, I'm testing out multi-line list descriptions for the first time.

Early June pull

---

data/FilterList.json
data/FilterListMaintainer.json
data/FilterListTag.json
data/Maintainer.json

I decided to take care of https://github.com/collinbarrett/FilterLists/issues/799 to the degree I felt like doing so.

Early June pull 2

---

data/FilterList.json
data/FilterListTag.json

Add a lite version of the urlhaus blocklist (https://github.com/collinbarrett/FilterLists/pull/608).

add URLhaus lite blocklist

---

data/FilterList.json
data/FilterListMaintainer.json
data/FilterListTag.json
data/Tag.json

* Created a new tag called `cultural` and spun off ~40 `topical`-taggings into it.
* Added my 3 newest lists, and 1 from another guy.
* Corrected some minor grammar errors from my previous pull.

Late June pull

---

data/FilterList.json
data/FilterListMaintainer.json
data/FilterListTag.json
data/Tag.json

* Added my 3 newest lists.
* Added an additional note for the `social` tag, since it is for the time being also being used for anti-comment-sections lists.

Late June pull 3

---

data/FilterList.json
data/FilterListLanguage.json
data/FilterListTag.json
data/Maintainer.json
data/Software.json

* Attempted to see how much of #836 I could take care of.
* Added 1 new list.
* Removed *Optimized PI Hole HOSTS* for being a less elaborate duplicate entry for *OISD Mobile*.

Early July pull

---

data/FilterList.json
data/FilterListLanguage.json
data/FilterListTag.json
data/License.json

I seem to have found a bunch of uMatrix lists(?), basically.

Early July pull 3

---

data/FilterList.json
data/FilterListLanguage.json
data/FilterListTag.json

• Discovered 7 more lists over the past week, most of them from the maintainers of established regional lists.
• Assigned languages to more *Pi-Hole Parser* lists.

Late July pull

---

data/FilterList.json
data/FilterListLanguage.json
data/FilterListMaintainer.json
data/FilterListTag.json

While looking into #886, I discovered that quite a few of the lists he was using as his sources, had not been added to FilterLists yet. And so I once again felt morally obliged to add them here, as well as a few other ones.

Added 40 lists

---

data/FilterList.json
data/FilterListLanguage.json
data/FilterListMaintainer.json
data/FilterListTag.json
data/Maintainer.json

Added Mmoti's Regex Filters for Pi-hole and made small fixes, reindented lines with VS Code.

New list and small fixes

---

data/FilterList.json
data/FilterListMaintainer.json
data/FilterListTag.json

* Added my new list
* Linked it to myself as the maintainer
* Set the tags as `Blocks specific topics/things` and `Blocks resources from certain companies`

Add my new facebook/messenger/instagram block list

---

data/FilterList.json
data/FilterListLanguage.json
data/FilterListMaintainer.json
data/FilterListTag.json

• Added 13 new lists (incl. dealing with #912), which is pretty much the only thing I did this time.

Late August pull

---

data/FilterList.json
data/FilterListMaintainer.json
data/FilterListTag.json
data/Maintainer.json

This is my filterlist for removing those Push Notification prompts from what sadly now seems to be every news site.

Add DontPushMe list for filtering push notifications

---

data/FilterList.json
data/FilterListLanguage.json
data/FilterListMaintainer.json
data/FilterListTag.json

* Added my 3 newest lists.
* Removed 2 lists that I had deleted.
* Minor metadata brushup.

Mid-September pull

---

data/FilterList.json
data/FilterListLanguage.json
data/FilterListMaintainer.json
data/FilterListTag.json

Added 30 lists and made some info corrections.

Mid-October pull 2

---

data/FilterList.json
data/FilterListLanguage.json
data/FilterListMaintainer.json
data/FilterListTag.json
data/License.json
data/Software.json
data/Syntax.json

It was overdue that I made a big pull, as I'll be busy for most of the next three weeks with completely different things.
I also took care of #1074, #1108, #1114, and #1123.

Early November pull

---

data/FilterList.json
data/FilterListLanguage.json
data/FilterListMaintainer.json
data/FilterListTag.json
data/SoftwareSyntax.json

I added 11 new lists and 2 syntax/software supports, most of all.

Late November pull

---

data/lint.sh
server/azure-pipelines.migrate.yaml

feat(data): lint json on data change via migrate

---

docker-compose.override.yml
docker-compose.prod.yml

ref https://github.com/docker/compose/pull/1765

fix(reverse-proxy): 🐛 fix ports var interpolation

---

web/src/App.tsx

Should fix https://github.com/collinbarrett/FilterLists/issues/937

Fix react router paths to show error page on undefined pages

---

services/Directory/data/FilterList.json
services/Directory/data/FilterListLanguage.json
services/Directory/data/FilterListSyntax.json
services/Directory/data/FilterListTag.json
services/Directory/data/FilterListViewUrl.json

Hope I have done everything correct.

Add EasyDutch

---

services/Directory/FilterLists.Directory.Infrastructure.Migrations/Migrations/20210403022856_2309.Designer.cs
services/Directory/FilterLists.Directory.Infrastructure.Migrations/Migrations/20210403022856_2309.cs
services/Directory/data/FilterList.json
services/Directory/data/FilterListMaintainer.json
services/Directory/data/FilterListSyntax.json
services/Directory/data/FilterListTag.json
services/Directory/data/FilterListViewUrl.json
services/Directory/data/Maintainer.json

- add maintainer
- fix(phishing-filter): update url

feat(urlhaus/phishing-filter): add RPZ blocklists

---

services/Directory/FilterLists.Directory.Infrastructure.Migrations/Migrations/20210424221556_2332.Designer.cs
services/Directory/FilterLists.Directory.Infrastructure.Migrations/Migrations/20210424221556_2332.cs
services/Directory/data/FilterList.json

https://github.com/beerisgood/beer_blocklist

add beer_blocklist

---

services/Directory/FilterLists.Directory.Infrastructure.Migrations/Migrations/20210428105221_2343.Designer.cs
services/Directory/FilterLists.Directory.Infrastructure.Migrations/Migrations/20210428105221_2343.cs
services/Directory/data/FilterList.json
services/Directory/data/FilterListLanguage.json
services/Directory/data/FilterListMaintainer.json
services/Directory/data/FilterListSyntax.json
services/Directory/data/FilterListTag.json
services/Directory/data/FilterListViewUrl.json

May cause conflicts with the existing PRs.

Add Yuki's Blogroll filters and some updates

---

services/Directory/FilterLists.Directory.Infrastructure.Migrations/Migrations/20210428122336_2342.Designer.cs
services/Directory/FilterLists.Directory.Infrastructure.Migrations/Migrations/20210428122336_2342.cs
services/Directory/data/FilterList.json
services/Directory/data/FilterListLanguage.json
services/Directory/data/FilterListMaintainer.json
services/Directory/data/FilterListSyntax.json
services/Directory/data/FilterListTag.json
services/Directory/data/FilterListViewUrl.json
services/Directory/data/Maintainer.json

Hi, I would like to add my filter to your project. Thank you.

Add Konayuki filters

---

services/Directory/FilterLists.Directory.Infrastructure.Migrations/Migrations/20210502112836_2352.Designer.cs
services/Directory/FilterLists.Directory.Infrastructure.Migrations/Migrations/20210502112836_2352.cs
services/Directory/data/FilterList.json
services/Directory/data/FilterListMaintainer.json
services/Directory/data/FilterListSyntax.json
services/Directory/data/FilterListTag.json
services/Directory/data/FilterListViewUrl.json

- A block of websites that host potentially unwanted programs

feat: add pup-filter

---

services/Directory/FilterLists.Directory.Infrastructure.Migrations/Migrations/20210503162839_2358.Designer.cs
services/Directory/FilterLists.Directory.Infrastructure.Migrations/Migrations/20210503162839_2358.cs
services/Directory/data/FilterList.json

Adding XPI FIlterlist I hope that I did this correctly

xpi filterlist

---

services/Directory/FilterLists.Directory.Infrastructure.Migrations/Migrations/20210503165446_2359.Designer.cs
services/Directory/FilterLists.Directory.Infrastructure.Migrations/Migrations/20210503165446_2359.cs
services/Directory/data/FilterListTag.json

Resubmitting tag for XPI filterlist due to failures

Resubmit tags for Filterlsit

---

services/Directory/FilterLists.Directory.Infrastructure.Migrations/Migrations/20210504145343_2362.Designer.cs
services/Directory/FilterLists.Directory.Infrastructure.Migrations/Migrations/20210504145343_2362.cs
services/Directory/data/FilterList.json

Added email for contacting regarding issues or comments

Added email for contacting

---

services/Directory/FilterLists.Directory.Infrastructure.Migrations/Migrations/20210504161622_2363.Designer.cs
services/Directory/FilterLists.Directory.Infrastructure.Migrations/Migrations/20210504161622_2363.cs
services/Directory/data/FilterList.json
services/Directory/data/FilterListViewUrl.json

Please change any other places to change too.

address #2361

---

services/Directory/FilterLists.Directory.Infrastructure.Migrations/Migrations/20210506004048_2368.Designer.cs
services/Directory/FilterLists.Directory.Infrastructure.Migrations/Migrations/20210506004048_2368.cs
services/Directory/data/FilterListMaintainer.json
services/Directory/data/FilterListSyntax.json
services/Directory/data/Maintainer.json

creating a new PR since #2367 was from fork's `master` branch that I don't have push rights to

fixing #2367

---

services/Directory/FilterLists.Directory.Infrastructure.Migrations/Migrations/20210509223212_2373.Designer.cs
services/Directory/FilterLists.Directory.Infrastructure.Migrations/Migrations/20210509223212_2373.cs
services/Directory/data/FilterList.json
services/Directory/data/FilterListMaintainer.json
services/Directory/data/FilterListSyntax.json
services/Directory/data/FilterListTag.json
services/Directory/data/FilterListViewUrl.json

Closes collinbarrett/FilterLists#2338

Add AdGuard url tracking 

---

services/Directory/FilterLists.Directory.Infrastructure.Migrations/Migrations/20210509223926_2375.Designer.cs
services/Directory/FilterLists.Directory.Infrastructure.Migrations/Migrations/20210509223926_2375.cs
services/Directory/data/FilterList.json

Update name and changes license

Update Columbia filter

---

services/Directory/FilterLists.Directory.Infrastructure.Migrations/Migrations/20210524083921_2403.Designer.cs
services/Directory/FilterLists.Directory.Infrastructure.Migrations/Migrations/20210524083921_2403.cs
services/Directory/data/FilterList.json
services/Directory/data/FilterListMaintainer.json
services/Directory/data/FilterListSyntax.json
services/Directory/data/FilterListTag.json
services/Directory/data/FilterListViewUrl.json

May month pull

---

services/Directory/FilterLists.Directory.Infrastructure.Migrations/Migrations/20210706210228_2452.Designer.cs
services/Directory/FilterLists.Directory.Infrastructure.Migrations/Migrations/20210706210228_2452.cs
services/Directory/data/FilterList.json
services/Directory/data/FilterListMaintainer.json
services/Directory/data/FilterListSyntax.json
services/Directory/data/FilterListTag.json
services/Directory/data/FilterListViewUrl.json
services/Directory/data/Maintainer.json

- added myself (`DRSDavidSoft`) as the maintainer to the lists already existing here :)
- added one of my new lists (fake, counterfeit/scam domains)
First time PR here.  I hope the commit format is correct; if not, I'd like to apologize, please advise how to correctly submit a PR.
Thank you!
---
Also, I'm not sure wether I made a mistake regarding tags (e.g. `directory-data`), or the tags should be added by you.

Add maintainer info and new list

---

services/Directory/FilterLists.Directory.Infrastructure.Migrations/Migrations/20210812064808_2504.Designer.cs
services/Directory/FilterLists.Directory.Infrastructure.Migrations/Migrations/20210812064808_2504.cs
services/Directory/data/FilterListViewUrl.json

`https://raw.githubusercontent.com/BPower0036/AdBlockFilters/main/easydutch`
to
`https://raw.githubusercontent.com/BPower0036/AdBlockFilters/main/easydutch.txt`

Update FilterListViewUrl EasyDutch

---

services/Directory/FilterLists.Directory.Infrastructure.Migrations/Migrations/20210907154345_2538.Designer.cs
services/Directory/FilterLists.Directory.Infrastructure.Migrations/Migrations/20210907154345_2538.cs
services/Directory/data/FilterList.json
services/Directory/data/FilterListMaintainer.json
services/Directory/data/FilterListSyntax.json
services/Directory/data/FilterListTag.json
services/Directory/data/FilterListViewUrl.json

* Added 13 lists and 1 mirror.
* Corrected 1 syntax.

Early September pull

---

services/Directory/FilterLists.Directory.Infrastructure.Migrations/Migrations/20211029231847_2616.Designer.cs
services/Directory/FilterLists.Directory.Infrastructure.Migrations/Migrations/20211029231847_2616.cs
services/Directory/data/FilterList.json
services/Directory/data/FilterListMaintainer.json
services/Directory/data/FilterListSyntax.json
services/Directory/data/FilterListTag.json
services/Directory/data/FilterListViewUrl.json
services/Directory/data/Maintainer.json

feat(api-data): ✨ add ammnt's lists #2445

---

services/Directory/FilterLists.Directory.Infrastructure.Migrations/Migrations/20211113123939_2662.Designer.cs
services/Directory/FilterLists.Directory.Infrastructure.Migrations/Migrations/20211113123939_2662.cs
services/Directory/azure-pipelines.migrate.yaml
services/Directory/data/FilterList.json
services/Directory/data/FilterListTag.json
services/Directory/data/FilterListViewUrl.json

This adds some tags to my lists (which I forgot last time) and adds the domains version

Some minor updates

---

services/Directory/FilterLists.Directory.Infrastructure.Migrations/Migrations/20211114123724_2665.Designer.cs
services/Directory/FilterLists.Directory.Infrastructure.Migrations/Migrations/20211114123724_2665.cs
services/Directory/data/FilterListMaintainer.json

Fix https://github.com/collinbarrett/FilterLists/issues/2663

---

services/Directory/FilterLists.Directory.Infrastructure.Migrations/Migrations/20211116121514_2671.Designer.cs
services/Directory/FilterLists.Directory.Infrastructure.Migrations/Migrations/20211116121514_2671.cs
services/Directory/data/FilterList.json

Due to an accident, the description of the _ClearURLs for uBo_ list was set to the description of another list.
This PR fixes that small error

Fix the description of the ClearURLs for uBo list

---

services/Directory/FilterLists.Directory.Infrastructure.Migrations/Migrations/20211208144405_2709.Designer.cs
services/Directory/FilterLists.Directory.Infrastructure.Migrations/Migrations/20211208144405_2709.cs
services/Directory/data/FilterListViewUrl.json

Is this enough or is there another file I have to change if I want to add mirrors to my filterlist (https://github.com/collinbarrett/FilterLists/pull/2508)

Add 2 mirrors

---

services/Directory/FilterLists.Directory.Infrastructure.Migrations/Migrations/20211219065506_2730.Designer.cs
services/Directory/FilterLists.Directory.Infrastructure.Migrations/Migrations/20211219065506_2730.cs
services/Directory/data/FilterList.json
services/Directory/data/FilterListLanguage.json
services/Directory/data/FilterListMaintainer.json
services/Directory/data/FilterListSyntax.json
services/Directory/data/FilterListTag.json
services/Directory/data/FilterListViewUrl.json

It turned out, despite previous notice of going unavailable, 280blocker list will be available for a while so I'll also keep Anti-scam enhancer for 280blocker adblock filter. OTOH I'll soon remove some of my lists as previously noticed in my HP.

Partly revert #2534 and remove a few lists

---

services/Directory/FilterLists.Directory.Infrastructure.Migrations/Migrations/20220109090829_2756.Designer.cs
services/Directory/FilterLists.Directory.Infrastructure.Migrations/Migrations/20220109090829_2756.cs
services/Directory/data/FilterListViewUrl.json

- https://gitlab.com/curben/urlhaus-filter/-/commit/8c94ddba40d794b194f614091a84f5fc1d00a4b0
- https://gitlab.com/curben/phishing-filter/-/commit/6cb2cbff6e1cd0fa97dafbe7199a5e54f5e23155

fix(curben filters): remove deprecated mirrors

---

services/Directory/FilterLists.Directory.Infrastructure.Migrations/Migrations/20220329171201_2860.Designer.cs
services/Directory/FilterLists.Directory.Infrastructure.Migrations/Migrations/20220329171201_2860.cs
services/Directory/data/FilterList.json
services/Directory/data/FilterListLanguage.json
services/Directory/data/FilterListMaintainer.json
services/Directory/data/FilterListSyntax.json
services/Directory/data/FilterListTag.json
services/Directory/data/FilterListViewUrl.json
services/Directory/data/Maintainer.json

https://github.com/List-KR/List-KR/issues/223
https://github.com/List-KR/List-KR#how-to-use

Add List-KR uBO and Update List-KR

---

services/Directory/FilterLists.Directory.Infrastructure.Migrations/Migrations/20220408114254_2873.Designer.cs
services/Directory/FilterLists.Directory.Infrastructure.Migrations/Migrations/20220408114254_2873.cs
services/Directory/data/FilterList.json

See https://github.com/collinbarrett/FilterLists/issues/2849

#2849 - Update all abpchina.org links

---

services/Directory/FilterLists.Directory.Infrastructure.Migrations/Migrations/20220411023546_2876.Designer.cs
services/Directory/FilterLists.Directory.Infrastructure.Migrations/Migrations/20220411023546_2876.cs
services/Directory/data/FilterList.json
services/Directory/data/FilterListLanguage.json
services/Directory/data/FilterListMaintainer.json
services/Directory/data/FilterListSyntax.json
services/Directory/data/FilterListViewUrl.json

- https://gitlab.com/curben/vn-badsite-filter

feat(filter): add vn-badsite-filter

---

services/Directory/FilterLists.Directory.Infrastructure.Migrations/Migrations/20220411155851_2879.Designer.cs
services/Directory/FilterLists.Directory.Infrastructure.Migrations/Migrations/20220411155851_2879.cs
services/Directory/data/Maintainer.json

https://github.com/piquark6046
https://github.com/List-KR/List-KR/issues/223

Change my primary email address

---

services/Directory/FilterLists.Directory.Infrastructure.Migrations/Migrations/20220415095451_2896.Designer.cs
services/Directory/FilterLists.Directory.Infrastructure.Migrations/Migrations/20220415095451_2896.cs
services/Directory/data/FilterListViewUrl.json

Made an mistake with some of the urls

Update FilterListViewUrl.json for EasyDutch

---

services/Directory/FilterLists.Directory.Infrastructure.Migrations/Migrations/20220415154139_2897.Designer.cs
services/Directory/FilterLists.Directory.Infrastructure.Migrations/Migrations/20220415154139_2897.cs
services/Directory/data/FilterList.json
services/Directory/data/FilterListMaintainer.json
services/Directory/data/FilterListSyntax.json
services/Directory/data/FilterListTag.json
services/Directory/data/FilterListViewUrl.json
services/Directory/data/Maintainer.json
services/Directory/data/Tag.json

feat(dir): ✨ add Syncthing Relay Server IPs

---

services/Directory/FilterLists.Directory.Infrastructure.Migrations/Migrations/20220415170612_2900.Designer.cs
services/Directory/FilterLists.Directory.Infrastructure.Migrations/Migrations/20220415170612_2900.cs
services/Directory/data/FilterList.json
services/Directory/data/FilterListLanguage.json
services/Directory/data/FilterListMaintainer.json
services/Directory/data/FilterListSyntax.json
services/Directory/data/FilterListViewUrl.json
services/Directory/data/Maintainer.json

feat(dir): ✨ add Project RnJlRUhL

---

services/Directory/FilterLists.Directory.Infrastructure.Migrations/Migrations/20220415171735_2901.Designer.cs
services/Directory/FilterLists.Directory.Infrastructure.Migrations/Migrations/20220415171735_2901.cs
services/Directory/data/FilterList.json
services/Directory/data/FilterListViewUrl.json

fix(dir): 🐛 udpate dead link for Kees1958 list

---

services/Directory/FilterLists.Directory.Infrastructure.Migrations/Migrations/20220415172922_2902.Designer.cs
services/Directory/FilterLists.Directory.Infrastructure.Migrations/Migrations/20220415172922_2902.cs
services/Directory/data/FilterList.json
services/Directory/data/FilterListMaintainer.json
services/Directory/data/FilterListSyntax.json
services/Directory/data/FilterListViewUrl.json
services/Directory/data/Maintainer.json

feat(dir): ✨ add Anti-Q

---

services/Directory/FilterLists.Directory.Infrastructure.Migrations/Migrations/20220415174155_2903.Designer.cs
services/Directory/FilterLists.Directory.Infrastructure.Migrations/Migrations/20220415174155_2903.cs
services/Directory/data/FilterList.json
services/Directory/data/FilterListLanguage.json
services/Directory/data/FilterListSyntax.json
services/Directory/data/FilterListViewUrl.json
services/Directory/data/Syntax.json

feat(dir): ✨ add BlockListNetUA

---

services/Directory/FilterLists.Directory.Infrastructure.Migrations/Migrations/20220415175501_2904.Designer.cs
services/Directory/FilterLists.Directory.Infrastructure.Migrations/Migrations/20220415175501_2904.cs
services/Directory/data/FilterList.json
services/Directory/data/FilterListMaintainer.json
services/Directory/data/FilterListSyntax.json
services/Directory/data/FilterListViewUrl.json
services/Directory/data/Maintainer.json

feat(dir): ✨ add CytroxList

---

services/Directory/FilterLists.Directory.Infrastructure.Migrations/Migrations/20220415180718_2905.Designer.cs
services/Directory/FilterLists.Directory.Infrastructure.Migrations/Migrations/20220415180718_2905.cs
services/Directory/data/FilterList.json
services/Directory/data/FilterListMaintainer.json
services/Directory/data/FilterListSyntax.json
services/Directory/data/FilterListTag.json
services/Directory/data/FilterListViewUrl.json
services/Directory/data/Maintainer.json

feat(dir): ✨ add No Google (Unbound)

---

services/Directory/FilterLists.Directory.Infrastructure.Migrations/Migrations/20220415191140_2908.Designer.cs
services/Directory/FilterLists.Directory.Infrastructure.Migrations/Migrations/20220415191140_2908.cs
services/Directory/data/FilterList.json
services/Directory/data/FilterListMaintainer.json
services/Directory/data/FilterListSyntax.json
services/Directory/data/FilterListTag.json
services/Directory/data/FilterListViewUrl.json
services/Directory/data/Maintainer.json

feat(dir): ✨ add gnX Threat Intelligence

---

services/Directory/FilterLists.Directory.Infrastructure.Migrations/Migrations/20220415200716_2909.Designer.cs
services/Directory/FilterLists.Directory.Infrastructure.Migrations/Migrations/20220415200716_2909.cs
services/Directory/data/FilterList.json
services/Directory/data/FilterListMaintainer.json
services/Directory/data/FilterListSyntax.json
services/Directory/data/FilterListTag.json
services/Directory/data/FilterListViewUrl.json
services/Directory/data/Maintainer.json

 feat(dir): ✨ add ThreatShare & Bank of Lithuania Illegal websites 

---

services/Directory/FilterLists.Directory.Infrastructure.Migrations/Migrations/20220518221549_3063.Designer.cs
services/Directory/FilterLists.Directory.Infrastructure.Migrations/Migrations/20220518221549_3063.cs
services/Directory/data/FilterList.json
services/Directory/data/FilterListSyntax.json
services/Directory/data/FilterListTag.json
services/Directory/data/FilterListViewUrl.json

Replace Zelos referral whitelist

---

services/Directory/FilterLists.Directory.Infrastructure.Migrations/Migrations/20220603130157_3114.cs
services/Directory/data/FilterList.json
services/Directory/data/FilterListTag.json

In light of their list now embedding https://raw.githubusercontent.com/abp-filters/abp-filters-hotfix/main/hotfix.txt, which whitelists all Admiral domains and some other major domains, any perceptions from years ago that the list is AAB have been debunked once and for all, hastily necessitating name changes, tag changes, and even description removals in order to face this new reality.

Major hotfix for ABP Filters

---

services/Directory/FilterLists.Directory.Infrastructure.Migrations/Migrations/20220712222900_3177.cs
services/Directory/data/FilterList.json

It was my own list which I no longer wish to maintain.

Remove 0131-block-list

---

services/Directory/FilterLists.Directory.Infrastructure.Migrations/Migrations/20220817173459_3236.cs
services/Directory/data/FilterList.json
services/Directory/data/FilterListViewUrl.json

* Changed "PersianPiHole" to "PersianBlockerHosts"
* Changed license from GPLv3 to AGPLv3

Update PersianBlocker info

---

services/Directory/FilterLists.Directory.Infrastructure.Migrations/Migrations/20220828193025_3248.cs
services/Directory/data/FilterList.json
services/Directory/data/FilterListMaintainer.json
services/Directory/data/FilterListSyntax.json
services/Directory/data/FilterListTag.json
services/Directory/data/FilterListViewUrl.json

AdGuard recently split their Annoyances Filter into 5 parts (though the original mega-list also still exists), and also changed [their folder tree](https://github.com/AdguardTeam/AdguardFilters/tree/master/AnnoyancesFilter) in the process, necessitating this PR.
I also added my newest list as well.

Fix for AdGuard Annoyances' new official lists

---

services/Directory/FilterLists.Directory.Infrastructure.Migrations/Migrations/20221001141551_3284.cs
services/Directory/data/FilterListViewUrl.json

refactor(db): ♻️ mv huzunluartemis from GH to GL

---

services/Directory/FilterLists.Directory.Infrastructure.Migrations/Migrations/20221001142614_3285.cs
services/Directory/data/FilterList.json
services/Directory/data/FilterListMaintainer.json
services/Directory/data/FilterListSyntax.json
services/Directory/data/FilterListViewUrl.json
services/Directory/data/Maintainer.json

feat(db): ✨ add AdAway Default Blocklist (AdGuard Version)

---

services/Directory/FilterLists.Directory.Infrastructure.Migrations/Migrations/20221001171639_3286.cs
services/Directory/data/FilterList.json
services/Directory/data/FilterListMaintainer.json
services/Directory/data/FilterListSyntax.json
services/Directory/data/FilterListViewUrl.json
services/Directory/data/Maintainer.json

feat(db): ✨ add Inversion CloudIPs

---

services/Directory/FilterLists.Directory.Infrastructure.Migrations/Migrations/20221001175352_3287.cs
services/Directory/data/FilterList.json
services/Directory/data/FilterListMaintainer.json
services/Directory/data/FilterListSyntax.json
services/Directory/data/FilterListViewUrl.json
services/Directory/data/Maintainer.json

closes #3010
closes #3045 
closes #3051

feat(db): ✨ add The Doggy Brad's lists

---

services/Directory/FilterLists.Directory.Infrastructure.Migrations/Migrations/20230116201943_3389.cs
services/Directory/data/FilterListViewUrl.json

Updated the CDN's and put my lists together, which makes is easier for me to added my lists.

Update my filterlists

---

services/Directory/FilterLists.Directory.Infrastructure.Migrations/Migrations/20230118054002_3391.cs
services/Directory/data/FilterList.json
services/Directory/data/FilterListMaintainer.json
services/Directory/data/FilterListSyntax.json
services/Directory/data/FilterListTag.json
services/Directory/data/FilterListViewUrl.json

Added 4 lists

---

services/Directory/FilterLists.Directory.Infrastructure.Migrations/Migrations/20230217223539_3435.cs
services/Directory/data/FilterList.json
services/Directory/data/FilterListViewUrl.json

llacb47 has renamed their/his/her account to liamengland1, meaning the links on filterlists.com are now broken.
This PR should fix this
@liamengland1 is this look ok?

llacb47 is now liamengland1

---

services/Directory/FilterLists.Directory.Infrastructure.Migrations/Migrations/20230224001747_3440.cs
services/Directory/data/FilterList.json
services/Directory/data/FilterListMaintainer.json
services/Directory/data/FilterListSyntax.json
services/Directory/data/FilterListTag.json
services/Directory/data/FilterListViewUrl.json

Some 2 years after I had initially created the list, I noticed by chance a few days ago that I most likely never uploaded it to FilterLists back in the days. 😅

Added 1 missing list

---

services/Directory/FilterLists.Directory.Infrastructure.Migrations/Migrations/20230307012331_3452.cs
services/Directory/data/FilterList.json

Forgot to smooth a few things over in my last PR. Many thanks for continuing to maintain this site and database.

Further updates and corrections to my lists.

---

services/Directory/FilterLists.Directory.Infrastructure.Migrations/Migrations/20230308210352_3456.cs
services/Directory/data/FilterList.json
services/Directory/data/FilterListMaintainer.json
services/Directory/data/FilterListSyntax.json
services/Directory/data/FilterListTag.json
services/Directory/data/FilterListViewUrl.json
services/Directory/data/Maintainer.json

With necessary corrections and additional files. Apologies for the earlier oversights. A bit scattered today I guess.

Previously aborted PR (new lists, tags, etc...).

---

services/Directory/FilterLists.Directory.Infrastructure.Migrations/Migrations/20230308220956_3457.cs
services/Directory/data/FilterListSyntax.json

That's it for my stuff, and again, sorry for the botched PR from earlier. Godspeed!

And finally, syntax correction.

---

services/Directory/FilterLists.Directory.Infrastructure.Migrations/Migrations/20230322131009_3486.cs
services/Directory/data/FilterListViewUrl.json

re-do #3485

---

services/Directory/FilterLists.Directory.Infrastructure.Migrations/Migrations/20230323075458_3487.cs
services/Directory/data/FilterList.json
services/Directory/data/FilterListLanguage.json
services/Directory/data/FilterListSyntax.json
services/Directory/data/FilterListViewUrl.json

Somehow `https://filterlists.com/lists/easylist-dutch-johnyp36` is added to the website, but this is double with `https://filterlists.com/lists/dutch-filter-list` as you can see if you look up the list *and maintainer*. 
So, I removed this from every file. 
Also, I made some changes as their were some incorrectness in the main filterlist (`https://filterlists.com/lists/dutch-filter-list` / `filterListId: 2519`)

Remove double filterlist

---

services/Directory/FilterLists.Directory.Infrastructure.Migrations/Migrations/20230404222243_3503.cs
services/Directory/data/FilterList.json
services/Directory/data/FilterListMaintainer.json
services/Directory/data/FilterListSyntax.json
services/Directory/data/FilterListTag.json
services/Directory/data/FilterListViewUrl.json

As it is about two years old, is included in a few compilation lists, and seems fairly stable, I have added my VXVault filterlist to filterlists.com. Hopefully I haven't forgotten anything.
Additionally, I updated the name and description of my existing list, in addition to adding my email address.
Thank you

Add my unoffical VXVault filter & update my other lists

---

services/Directory/FilterLists.Directory.Infrastructure.Migrations/Migrations/20230408110844_3505.cs
services/Directory/data/FilterList.json
services/Directory/data/FilterListViewUrl.json

mypdns's lists have been moved to https://0xacab.org/my-privacy-dns
This PR should update filterlists.com to use the correct URLs.

Update mypdns lists

---

services/Directory/FilterLists.Directory.Infrastructure.Migrations/Migrations/20230418184752_3536.cs
services/Directory/data/FilterList.json
services/Directory/data/FilterListMaintainer.json
services/Directory/data/FilterListSyntax.json
services/Directory/data/FilterListViewUrl.json

fix some thedoggybrad lists for #3322

---

services/Directory/FilterLists.Directory.Infrastructure.Migrations/Migrations/20230418190638_3537.cs
services/Directory/data/FilterList.json
services/Directory/data/FilterListTag.json
services/Directory/data/FilterListViewUrl.json

feat(data): ✨ add 1275.ru DGA general list

---

services/Directory/FilterLists.Directory.Infrastructure.Migrations/Migrations/20230418195454_3539.cs
services/Directory/data/FilterListMaintainer.json
services/Directory/data/FilterListViewUrl.json

chore(data): ♻️  updates to Adblock List for Finland

---

services/Directory/FilterLists.Directory.Infrastructure.Migrations/Migrations/20230425140636_3564.cs
services/Directory/data/FilterList.json
services/Directory/data/FilterListMaintainer.json
services/Directory/data/FilterListSyntax.json
services/Directory/data/FilterListTag.json
services/Directory/data/FilterListViewUrl.json
services/Directory/data/Maintainer.json

[(BlockModReposting GitHub Repo)](https://github.com/rotgruengelb/BlockModReposting)

Added BlockModReposting Block List.

---

services/Directory/FilterLists.Directory.Infrastructure.Migrations/Migrations/20230427142027_3569.cs
services/Directory/data/FilterList.json
services/Directory/data/FilterListMaintainer.json
services/Directory/data/FilterListSyntax.json
services/Directory/data/FilterListTag.json
services/Directory/data/FilterListViewUrl.json
services/Directory/data/Maintainer.json

Add @jarelllama's [scam blocklist](https://github.com/jarelllama/Scam-Blocklist).
Thank you.

Add Scam Blocklist

---

services/Directory/FilterLists.Directory.Infrastructure.Migrations/Migrations/20230925214046_3842.Designer.cs
services/Directory/FilterLists.Directory.Infrastructure.Migrations/Migrations/20230925214046_3842.cs
services/Directory/data/FilterList.json
services/Directory/data/FilterListViewUrl.json

This should hopefully update the abp anti circumvention filterlist.
Please tell me if I missed anything.
Thanks

Hopefully fix https://github.com/collinbarrett/FilterLists/issues/3841

---

services/Directory/FilterLists.Directory.Infrastructure.Migrations/Migrations/20231106215419_3892.Designer.cs
services/Directory/FilterLists.Directory.Infrastructure.Migrations/Migrations/20231106215419_3892.cs
services/Directory/data/FilterList.json
services/Directory/data/FilterListLanguage.json
services/Directory/data/FilterListSyntax.json
services/Directory/data/FilterListTag.json
services/Directory/data/FilterListViewUrl.json

Hi All.
Please check why one test fails.

Added RuBlock List for uBO

---

services/Directory/FilterLists.Directory.Infrastructure.Migrations/Migrations/20231109152857_3900.Designer.cs
services/Directory/FilterLists.Directory.Infrastructure.Migrations/Migrations/20231109152857_3900.cs
services/Directory/data/FilterListViewUrl.json

As of https://github.com/gorhill/uBlock/commit/d05ff8ffebf8a35a9048c52837fa60a7a55f222f I am supporting `Diff-patching` thus making that file as primariness 1.

Update url's for filterListId 2519

---

services/Directory/azure-pipelines.migrate.yaml

to resolve build issue in https://github.com/collinbarrett/FilterLists/pull/3951

fix(migrate): 🐛 pin migrate dotnet-ef version

---

services/Directory/FilterLists.Directory.Infrastructure.Migrations/Migrations/20240115150557_4045.Designer.cs
services/Directory/FilterLists.Directory.Infrastructure.Migrations/Migrations/20240115150557_4045.cs
services/Directory/data/FilterList.json
services/Directory/data/FilterListLanguage.json
services/Directory/data/FilterListMaintainer.json
services/Directory/data/FilterListSyntax.json
services/Directory/data/FilterListTag.json
services/Directory/data/FilterListViewUrl.json

It's been a rough time for me since mid-September, for sure. But I finally made the extra effort and some energy to spare to add the 5 newest lists that I can remember having made, at least.

Autumn / early Winter pull

---

services/Directory/FilterLists.Directory.Infrastructure.Migrations/Migrations/20240419125237_4247.Designer.cs
services/Directory/FilterLists.Directory.Infrastructure.Migrations/Migrations/20240419125237_4247.cs
services/Directory/data/FilterList.json
services/Directory/data/FilterListMaintainer.json
services/Directory/data/FilterListSyntax.json
services/Directory/data/FilterListTag.json
services/Directory/data/FilterListViewUrl.json
services/Directory/data/Maintainer.json

New filters added:
1. id: 2670 (Ukrainian Ad Filter)
2. id: 2671 (Ukrainian Annoyance Filter)
3. id: 2672 (Ukrainian Privacy Filter)
Updated information about the `Ukrainian Security Filter` (id: 2669): a link to a new donation page has been added

New filters added (id: 2670, id: 2671, id: 2672)

---

services/Directory/FilterLists.Directory.Infrastructure.Migrations/Migrations/20240429075309_4264.Designer.cs
services/Directory/FilterLists.Directory.Infrastructure.Migrations/Migrations/20240429075309_4264.cs
services/Directory/data/FilterListViewUrl.json

Reflected recent URL changes of 3 of my lists

---

services/Directory/FilterLists.Directory.Api/Dockerfile
web/Dockerfile

ref https://docs.github.com/en/packages/working-with-a-github-packages-registry/working-with-the-container-registry#pushing-container-images

feat(docker): ✨🔧 connect GH repo to Package

---

services/Directory/FilterLists.Directory.Api/OpenApi/OpenApiConfigurationExtension.cs

ref https://swagger.io/specification/#document-structure

refactor(dir): ♻️ ren OpenAPI spec to recommended name

---

services/Directory/FilterLists.Directory.Api/OpenApi/OpenApiConfigurationExtension.cs

This reverts commit dc6d91af93fff60b923249ab25b940e9f4895ae9.

Revert "refactor(dir): ♻️ ren OpenAPI spec to recommended name"

---

services/Directory/FilterLists.Directory.Api/CorsConfiguration.cs

ref https://github.com/collinbarrett/FilterLists/pull/4359

feat(dir): ✨🔓 allow CORS from Next.js staging

---

.github/workflows/directory-migrate.yml

ref https://github.com/collinbarrett/FilterLists/pull/4366

fix(dir-data): 🐛 try fix directory-migrate on PR from fork

---

.github/workflows/directory-migrate.yml
services/Directory/FilterLists.Directory.Infrastructure/ConfigurationExtensions.cs

ref https://github.com/collinbarrett/FilterLists/pull/4366

feat(dir-data): ✨ enable sensitive data logging in migration Action

---

services/Directory/FilterLists.Directory.Api/CorsConfiguration.cs
services/Directory/FilterLists.Directory.Infrastructure.Migrations/Migrations/20240617184643_4366.Designer.cs
services/Directory/FilterLists.Directory.Infrastructure.Migrations/Migrations/20240617184643_4366.cs
services/Directory/data/FilterList.json
services/Directory/data/FilterListMaintainer.json
services/Directory/data/FilterListSyntax.json
services/Directory/data/FilterListTag.json
services/Directory/data/FilterListViewUrl.json
services/Directory/data/Maintainer.json

Hey there, thanks for your great work maintaining this excellent resource.
I went ahead and created a PR to add my [BadBlock](https://github.com/Retold3202/BadBlock) project, as well as a couple lists from [Divested Computing Group](https://divested.dev/pages/dnsbl), & Ph00lt0's [blocklist](https://github.com/ph00lt0/blocklist).
Hope everything looks good, please let me know if there's any issues. :)

Add BadBlock, Divested, & Ph00lt0 Lists

---

services/Directory/FilterLists.Directory.Infrastructure.Migrations/Migrations/20240803174006_4451.Designer.cs
services/Directory/FilterLists.Directory.Infrastructure.Migrations/Migrations/20240803174006_4451.cs
services/Directory/data/FilterList.json
services/Directory/data/FilterListViewUrl.json

GIT repository changes: github.com/serhiyguryev/ukrainian-filters -> github.com/ukrainianfilters/lists

Changed URLs due to GIT repository changes (filterListId: 2669-2672)

---

services/Directory/FilterLists.Directory.Infrastructure.Migrations/Migrations/20240811163339_4458.Designer.cs
services/Directory/FilterLists.Directory.Infrastructure.Migrations/Migrations/20240811163339_4458.cs
services/Directory/data/FilterList.json
services/Directory/data/FilterListViewUrl.json

Update Bypass Paywalls Clean filter

---

web/package-lock.json
web/package.json

Reverts collinbarrett/FilterLists#4661

Revert "build(deps): bump react-router-dom from 5.3.4 to 7.1.1 in /web"

---

.github/workflows/codeql.yml
.github/workflows/directory-migrate.yml
.github/workflows/directory.yml
services/Directory/FilterLists.Directory.Api/FilterLists.Directory.Api.csproj
services/Directory/FilterLists.Directory.Application/FilterLists.Directory.Application.csproj
services/Directory/FilterLists.Directory.Infrastructure.Migrations/FilterLists.Directory.Infrastructure.Migrations.csproj
services/Directory/FilterLists.Directory.Infrastructure.Migrations/Migrations/20250215215404_4693.Designer.cs
services/Directory/FilterLists.Directory.Infrastructure.Migrations/Migrations/20250215215404_4693.cs
services/Directory/FilterLists.Directory.Infrastructure/FilterLists.Directory.Infrastructure.csproj
services/Directory/data/FilterList.json
services/Directory/data/FilterListViewUrl.json
services/Directory/data/Maintainer.json
services/FilterLists.AppHost/FilterLists.AppHost.csproj
services/FilterLists.ServiceDefaults/FilterLists.ServiceDefaults.csproj

migrate #4693 and upgrade to dotnet9

upgrade to dotnet9

---

services/Directory/FilterLists.Directory.Infrastructure.Migrations/Migrations/20250304001344_4735.Designer.cs
services/Directory/FilterLists.Directory.Infrastructure.Migrations/Migrations/20250304001344_4735.cs

feat(data): migrate #4735

---

services/Directory/FilterLists.Directory.Infrastructure.Migrations/Migrations/20250304002804_4735v2.Designer.cs
services/Directory/FilterLists.Directory.Infrastructure.Migrations/Migrations/20250304002804_4735v2.cs
services/Directory/data/FilterList.json

satisfy unique name constraint for #4735

fix(data): satisfy unique name constraint for #4735

---

services/Directory/FilterLists.Directory.Infrastructure.Migrations/Migrations/20250423004727_4795.Designer.cs
services/Directory/FilterLists.Directory.Infrastructure.Migrations/Migrations/20250423004727_4795.cs
services/Directory/data/FilterList.json
services/Directory/data/FilterListMaintainer.json
services/Directory/data/FilterListSyntax.json
services/Directory/data/FilterListTag.json
services/Directory/data/FilterListViewUrl.json
services/Directory/data/Maintainer.json

Hi,
this PR closes #4615
Regards.

[Add] Meta Platforms Blocklists

---

services/Directory/FilterLists.Directory.Infrastructure.Migrations/Migrations/20250508015706_4807.Designer.cs
services/Directory/FilterLists.Directory.Infrastructure.Migrations/Migrations/20250508015706_4807.cs
services/Directory/data/FilterList.json
services/Directory/data/FilterListLanguage.json
services/Directory/data/FilterListMaintainer.json
services/Directory/data/FilterListTag.json
services/Directory/data/FilterListViewUrl.json
services/Directory/data/Maintainer.json

My curated list of Bolloré, alt-right and french fascist web sites.
This is my first contribution on this project. Feel free to share any inputs to improve this PR :)

feat: add bloquebollore

---

services/Directory/FilterLists.Directory.Infrastructure.Migrations/Migrations/20250726191651_4985.Designer.cs
services/Directory/FilterLists.Directory.Infrastructure.Migrations/Migrations/20250726191651_4985.cs
services/Directory/data/Software.json
services/Directory/data/SoftwareSyntax.json

Its domain lapsed and now leads to a somewhat suspicious gambling site.

Removed hostsmgr
