data/lists.json

Clickbait Blocklist just blocks the most annoying clickbait ads. I don't mind ads; I just don't want clickbait crap about shocking celebrity photos and "deep searches" for local singles.

Add Clickbait Blocklist

---

data/lists.json

I've lost an access to my old GitHub account @hant0508, so I have to fork the repo and maintain it on a new address: https://github.com/hant05080/uBlock-filters

Changed link to @hant0508 filters

---

.github/README.md
data/FilterList.json
data/FilterListMaintainer.json

I sat on these first two lists of mine for some weeks, as I was concerned if they would come across to others as being somewhat hostile or not.
But as I feel that it's important for me to continue to show the world that adblockers can be used for so many more things than to block ads, and to also disprove all those editorials on techsites that seem to think of adblockers as an economic scam, I've added them here after all, in addition to a list that aims to prevent autoplay on YouTube.

Added 3 new lists and 2 software tools

---

data/FilterList.json

Having stumbled across #335, I decided to see how many of the HTTP list links that actually did support HTTPS after all, by pasting `##a[href*=https]` into Nano Adblocker's element selector, taking note of the subscription links that *weren't* highlighted, and then visiting them with [the **Smart HTTPS** extension](https://github.com/ilGur1132/Smart-HTTPS) turned on.
My findings were as follows:
✓ 1hosts
✓ 1hosts Addon
✓ Adblock List for Finland
✓ BadHosts
✓ BLOGRAM *
✓ Dan Pollock's Hosts
✓ DNS-BH *
✓ DShield.org (…)
✓ EasyList Lithuania
✓ Eesti Custom Sites Filter
✓ Finnish AntiSocial
✓ Firime (FED)
✓ Icelandic ABP List
✓ JAB Creations' (…)
✓ Japanese Site Adblock Filter *
✓ PLgeneral
✓ The Hosts File Project *
X Adblock Filters by Gurud.ee
X Airelle's *
X Ayucat Powerful List
X …

Upgraded supported list links to HTTPS

---

data/FilterList.json
data/FilterListLanguage.json
data/FilterListTag.json
data/Tag.json

Made some more additions.
I felt I had to clarify the "ie" tag a bit, since there technically exists amputated versions of Adblock Plus and AdGuard for IE that uses regular adblock lists, whereas the TPL lists make use of a different IE functionality that is mutually incompatible with those tools.

Saturday night pull

---

data/FilterList.json
data/FilterListTag.json
data/SoftwareSyntax.json

It seems that quite a few lists lacked syntaxIDs, which led to some odd omissions in the new software dropdown categories. So I've attempted to fix that here.
A bit of surface-level testing also indicates that uBO and Nano supports (most) URL and IP lists, so I tied those things together as well.

Tuesday afternoon pull

---

data/FilterList.json

I made a quick pull to test out the mirror linking. I chose to keep it pretty simple for now, only adding my own mirror and the non-uBO-hosted mirrors on their assets.json list.
I am also removing two lists of mine that I am planning to discontinue and delete in the very near future: *Norwegian Cashback Helper* because its functionality has long since been incorporated into the main Norwegian list (and because there was insufficient public demand to undo the incorporation), and the iOS list because I couldn't prove that it was even possible to add custom lists with that specific syntax to any iOS Safari extensions.

Testing out #467

---

data/FilterList.json
data/FilterListLanguage.json

The thought process behind 801-804 deserves an explanation:
I found myself looking through https://hg.adblockplus.org/subscriptionlist/file somehow, and saw some lists there that I had never seen before, including Macedonian and Tamil lists. I let out a sigh when I saw that several of them were hosted on Google Code, a host site that I thought had shut down completely in 2014. However, while testing a bit around with Archive.org and being redirected around a few times, I discovered that they were still hosted on the archive version of Google Code... with the code still intact! 🕺🎉
But the code was only available as part of ZIP files. I thought about it for some minutes, before realising *"Wait, why don't I host them myself?"*. And so it happened: …

Thursday morning pull

---

data/FilterList.json
data/FilterListLanguage.json
data/FilterListTag.json
data/License.json
data/Software.json
data/SoftwareSyntax.json
data/Syntax.json

Changelog:
• Added more correct licences to 60-ish lists.
• Listed 2 new licences to that effect.
• Removed *Filtros Nauscopicos Hosts*, since it was (as far as I could personally determine) just a mirror of Dan Pollock's Hosts from 2011.
• Attempted to add *dnsmasq* to both the software and syntax lists, based on some unclear instructions from https://github.com/notracking/hosts-blocklists#how-to-install.
I was slowly planning to begin to take care of maintainer IDs as well, but that'd take more time and different working methods than those I've used for this pull.

Tuesday evening pull

---

data/FilterList.json
data/FilterListLanguage.json
data/FilterListMaintainer.json
data/FilterListTag.json
data/License.json

I came across some more lists when browsing through GitHub, I suppose. 800 total lists hype! 🍰 
PS 1: I did come across a whole lot more lists, but it's come to a point where I've had to vet them a bit, even though this repo aims to collect every list in existence. For instance, I ruled out lists that were almost only of personal value (Example: https://github.com/SanderGit/adblock/blob/master/adblock.txt), that were too short (https://github.com/narrowfail/UyList/blob/master/uylist.txt), that I couldn't confirm if they were unique or not (https://raw.githubusercontent.com/joween18/adblocking/master/hosts.txt), or that were made by a brony (https://github.com/Akamaru/Pi-Hole-Lists). I won't stop any of you guys from adding whichever such lists you want to, but don't hold your hopes up for …

Saturday daytime pull

---

data/FilterList.json
data/FilterListMaintainer.json
data/FilterListTag.json
data/Software.json

This pull deals with two things:
• I've been doing some autumn cleaning on my personal-purposes-only list, and have begun to spin off some categories from it into lists that are more suitable for public use.
• The Chrome versions of Personal Blocklist no longer works. I've therefore made a few changes to coach Chrome users onto *Google Hit Hider by Domain*, which still works.

Tuesday night pull

---

data/Software.json
data/SoftwareSyntax.json

I know that FilterLists has a policy of not picking one software tool over another, but I've got some arguments that I want to voice.
I've given uBlock LLC the benefit of the doubt in the past 6 months, after they were bought out by AdBlock and promised big changes. Now that we're in November, it turns out that the changes have been... almost zero. Judging by https://github.com/uBlock-LLC/uBlock/commits/master: In the past 5 months they've made only 18 commits (20 commits if we count their Mac app repo).
* Their new website is confusing, and seems to me to have been hastily constructed to show off random information and their Mac app.
* Their included filterlists, as per https://github.com/uBlock-LLC/uBlock/blob/master/assets/ublock/filter-lists.json, is a disaster, with no one involved …

Removing non-Origin uBlock from the software list

---

data/FilterList.json
data/FilterListLanguage.json
data/FilterListMaintainer.json
data/FilterListTag.json
data/Maintainer.json

Holy cow, did I hit a goldmine while researching another repo. 🎉

Adding 378 lists

---

data/FilterList.json

About a month ago, I came to learn that Adblock Plus completely craps out when it's presented with a `:style` entry, resulting in both the list **and** all its entries refusing to work. Therefore I've decided to carefully look through various lists today, and to change the `syntaxId` of all lists that had even one `:style` entry from 3 to 4.
I also took care of #657 as well.

Corrected various syntaxes

---

data/FilterList.json
data/FilterListLanguage.json
data/FilterListMaintainer.json
data/FilterListTag.json
data/SoftwareSyntax.json
data/Syntax.json

A fair bit of maintenance.
* Added my 4 newest lists.
* Added a new syntax, for lists that are solely compilations of other lists through `#!include`. This was necessary to add, since AdGuard does not seem to me to support `!#include` in non-included lists.
* Changed the tags of 6 Shalla lists.
* Added a GitLab mirror for all of my 43 lists.
* Removed 2 lists: *Evidon Unbreaker* (Discontinued and deleted), and *Startshop ABP Filters* (The cashback service took their remaining money and ran, allowing their domain to expire).
* Updated the link to *Raajje-AdList*.
* Removed 5 lists by Deathbybandaid (and turned 2 others into mirrors of other lists), as they were domain versions of lists that were already domains-lists to begin with, and had fewer entries than the original lists as well.
* A …

Early February pull

---

data/FilterList.json
data/FilterListMaintainer.json
data/FilterListTag.json
data/Software.json
data/SoftwareSyntax.json
data/Syntax.json

* Added 2 new softwares: Unbound and BIND.
* Added 4 new syntaxes.
* Assigned various IDs to things.
* Added the Unbound and BIND versions of Peter Lowe's list.
* Turned ID 1522 into a mirror of 1520.
Known shortcomings:
* I discovered that there has previously been added various duplicates of the *Ultimate Hosts Blacklist* lists and of *JoeWein Email Sender Blacklist*, but I'm not feeling very awake today, so I didn't have enough energy to take care of them.
* I was tempted to remove *BadIPs* for not having a raw version, but I skipped that for the same reason.

Mid-March pull, part 1/2

---

src/FilterLists.Web/ClientApp/modules/home/components/softwareIcon/SoftwareIcon.tsx

As icon changes seem to take effect very quickly, I've now been able to see that I made some minor mistakes in #722, which I am fixing now, which should make sure that the correct icons get displayed.

Fixing the Unbound and BIND icons

---

data/FilterList.json
data/FilterListTag.json

This adds the [Hello, Goodbye!](https://hellogoodbye.app/) filter list, which the author extracted two days ago from their Chrome extension and Firefox add-on.
What I added to `FilterList.json`:
- `id`: 1530
- `viewUrl`: https://raw.githubusercontent.com/bcye/Hello-Goodbye/master/filterlist.txt
- `name`: Hello, Goodbye!
- `description`: Blocks every chat or helpdesk pop up in your browser.
- `emailAddress`: hello@hellogoodbye.app
- `homeUrl`: https://hellogoodbye.app/
- `issuesUrl`: https://github.com/bcye/Hello-Goodbye/issues
I didn’t set `syntax` because I’m not sure how to tell which syntax it is. From the examples on the [Syntax page](https://github.com/collinbarrett/FilterLists/wiki/Syntax), it looks to be closest to Adblock Plus format because of the leading `||`, but the list works …

Add filter list “Hello, Goodbye!”

---

src/FilterLists.Web/ClientApp/modules/home/components/detailsExpander/infoCard/UpdatedDate.tsx

At least the update dates were showing up again after the last pull, but they were still US-format-only.
But after discovering that `.toLocaleString()` has been successfully used for [the rule counter on the top of the page](https://github.com/collinbarrett/FilterLists/blob/master/src/FilterLists.Web/ClientApp/modules/home/components/Oneliner.tsx), I'll try it out for dates as well.

Date formatting, take 3

---

src/FilterLists.Web/ClientApp/modules/home/components/detailsExpander/infoCard/UpdatedDate.tsx

If `{props.ruleCount.toLocaleString()}` works in https://github.com/collinbarrett/FilterLists/blob/master/src/FilterLists.Web/ClientApp/modules/home/components/detailsExpander/infoCard/RuleCount.tsx, then surely `{props.updatedDate.toLocaleString()}` would have to work for dates as well, hopefully...

Date formatting, take 5

---

src/FilterLists.Web/ClientApp/modules/home/components/detailsExpander/infoCard/UpdatedDate.tsx

Contrary to how it may have looked like, take 5 was not a failure, as I learned from it that MomentJS is in fact not mandatory in order to display dates.
Although take 5 did make the dates display their full UTC timestamps á la `Updated: 2019-02-11T08:56:09`, so now comes the fine-tuning part.

Reverting the date formatting

---

data/FilterList.json
data/FilterListLanguage.json
data/FilterListMaintainer.json
data/FilterListTag.json
data/Syntax.json
data/Tag.json

This pull is a bit more down-to-earth than my code-editing attempts two weeks ago, and hopefully shouldn't be able to go awry. If I remember correctly:
* Removed *Bulgarian List (Domains)*, IIRC for being an inferior version of *ABP Bulgarian List (Domains)*.
* Added 3 new lists: *Breaking the News*, *Halt-and-Block-Mining*, and *AdmiraList*.
* Added 2 new tags: `newsletter` and `helpprompt`. I was unsure if "helpprompt" should be spelt as 1 word, but I went with it for now.
* Added 1 new syntax: Windows command line script.
* Switched some tag and language assignments around.
* And a few other miniscule edits.
I also recommend that the following example be added for "Windows command line script" on [the syntax wiki page]( https://github.com/collinbarrett/FilterLists/wiki/Syntax): `echo …

Mid-April pull

---

data/FilterList.json

Looks like general purpose csv. Comma separated list with domain, description, date, source(?).
[Malvaredomains.com](http://mirror1.malwaredomains.com/files/domains.txt) list is similar, but TAB separated, and columns are described in the header:
`##	nextvalidation	domain	type	original_reference-why_it_was_listed`

Not uBO compatible, not simple domains

---

data/FilterList.json
data/FilterListMaintainer.json
data/FilterListTag.json
data/Maintainer.json

I have several changes to my lists here:
1. Remove references to my base lists - leaving only the 'extended' ones. The base lists were never meant to be used directly and I should have had them more hidden in my directly structure when I first started
2. Update links to my lists to use the github pages link instead of the raw github link. The github pages links will respond with a `last-modified` header, so clients that are able to track modification times will run faster using the new links (pihole)
3. Add my third list - AMP Hosts - to block Accelerated Mobile Pages. Using tags `topical` and `anti-corp`
4. Add myself as a maintainer of my lists
Please let me know if I missed anything or more changes are necessary. Thank you!

Update my lists

---

data/Dependent.json
data/FilterList.json
data/FilterListMaintainer.json
data/SoftwareSyntax.json
data/Syntax.json

Added new syntax **Pi-hole regular expressions** also.
Because entries from regex list must be added manually, I created universal script for adding regex lists => https://raw.githubusercontent.com/PolishFiltersTeam/ScriptsPlayground/master/scripts/RLI_for_Pi-hole.sh. It downloads, installs lists and even updates it, so it can be added to cron for automatic updates of that lists. It's based on https://github.com/mmotti/pihole-regex/blob/master/install.sh. More at: `https://github.com/PolishFiltersTeam/ScriptsPlayground/blob/master/Readme_RLI_for_Pi-hole.md`

Add new Polish lists

---

data/SoftwareSyntax.json

Much to my surprise, some testing with sandbox lists of mine led me to discover that Blokada (and DNS66) really does support domains lists after all, and not just hosts files.
While I do still update #851 with things to do even after its de jure closure, this pull is meant as something a bit more hasteful and specific before I go to bed.

Hotfix for Blokada and DNS66

---

.github/README.md
data/TPLSubscriptionAssistant.html

(#974) Special thanks to @krystian3w for speculating on that Git fetchers (I've forgot what things like Githack are actually called) could allow HTML links.

Hotfix for #974

---

data/FilterList.json

Statically CDN recently updated their domain name. also move it to be the first mirror.

fix(urlhaus-filter): update statically cdn link

---

data/FilterList.json
data/FilterListLanguage.json
data/FilterListMaintainer.json
data/FilterListTag.json

Okay, so the situation is that after *1hosts Pro* was added to FilterLists.com, which listed its sources (which the other 1hosts versions still don't), I've come to learn that its maintainer has otherworldly skills at finding new lists, leading to https://github.com/collinbarrett/FilterLists/issues/851 being 60 lists long when I started making this pull, and I only got through 18 of them for the immediate time being.
I request the permanent re-opening of that issue report, as going through the rest of them is far beyond what I'd be able to do on my own.

Mid-October pull

---

data/FilterList.json

16 days ago they changed name and URL also.
https://github.com/easylist/easylist/commit/f479000932294df083fd5bde832bd03b7fd7176a

Fanboy's Cookiemonster List changed name to EasyList Cookie List

---

data/FilterList.json
data/SoftwareSyntax.json
data/Syntax.json

I just chose to take care of some of the more basic backlog stuff I had accumulated in the past month. Almost solely syntax-related things and some list source info.

Early January pull

---

data/FilterList.json

https://rawgit.com/ is closing.
This change removes a link
to rawgit and replaces
it with one to githack instead.

Remove link to rawgit.com

---

data/Dependent.json
data/Fork.json
data/License.json
data/Merge.json
data/Syntax.json

BOM encoding isn't a recommended
way to encode text files on
most operating systems.
Here data files with BOM
encoding have been changed
to UTF-8 without BOM.
This makes parsing the
json files much simpler.
https://stackoverflow.com/questions/2223882/whats-the-difference-between-utf-8-and-utf-8-without-bom

Remove BOM encoding from data files

---

services/Directory/FilterLists.Directory.Infrastructure.Migrations/Migrations/20210219184255_2240.Designer.cs
services/Directory/FilterLists.Directory.Infrastructure.Migrations/Migrations/20210219184255_2240.cs
services/Directory/data/FilterListViewUrl.json

I'm under the impression that github pages mean software like Pi Hole doesn't have to redownload files when they haven't changed, so I've changed the url to use github pages

 Changed mkb2091's lists to github pages

---

services/Directory/FilterLists.Directory.Infrastructure.Migrations/Migrations/20210902115704_2534.Designer.cs
services/Directory/FilterLists.Directory.Infrastructure.Migrations/Migrations/20210902115704_2534.cs
services/Directory/data/FilterList.json
services/Directory/data/FilterListLanguage.json
services/Directory/data/FilterListMaintainer.json
services/Directory/data/FilterListSyntax.json
services/Directory/data/FilterListTag.json
services/Directory/data/FilterListViewUrl.json

All 280blocker's filters are going to be private in mid Sept as bought by Tobila: `https://280blocker.net/blog/20210831/3043/`. Also nanj-kaishu-filter and nanj-kakuchou-filter are dead on GH (they are still available on `https://wikiwiki.jp/nanj-adguard/%E3%81%AA%E3%82%93J%E6%94%B9%E4%BF%AE%E3%83%95%E3%82%A3%E3%83%AB%E3%82%BF%E3%83%BC`, `https://wikiwiki.jp/nanj-adguard/%E3%81%AA%E3%82%93J%E6%8B%A1%E5%BC%B5%E3%83%95%E3%82%A3%E3%83%AB%E3%82%BF%E3%83%BC` but almost no more maintained, it's questionable if they're worth adding.) I'm going to remove Anti-scam enhancer for 280blocker adblock filter once I confirmed 280blocker adblock filter is inaccessible.
P.s. After this PR is merged I'll open a new PR to add my new list, all to avoid conflict.

Remove 280blocker and its related filters that are / going to be obsolete

---

services/Directory/FilterLists.Directory.Api.Contracts/Models/ListVm.cs
services/Directory/FilterLists.Directory.Application/Queries/GetLists.cs

resolves #2516 
just adding the "primary" `viewUrl` to this endpoint since it already returns a very large response. if the backup urls or urls for other "segments" are needed, then the list details endpoint for a specific list can still be used.

feat(dir): ✨ include primaryViewUrl in /lists endpoint

---

services/Directory/FilterLists.Directory.Infrastructure.Migrations/Migrations/20230816214511_3791.Designer.cs
services/Directory/FilterLists.Directory.Infrastructure.Migrations/Migrations/20230816214511_3791.cs
services/Directory/data/FilterList.json
services/Directory/data/FilterListSyntax.json
services/Directory/data/FilterListTag.json
services/Directory/data/FilterListViewUrl.json

This filterlist appears to have been deleted<sup>[[1]](https://github.com/blogmangit/Cosmetic-Filters/commit/4f1edae9d43985d67ff33dc39106337f89fa1e0d)</sup>. The maintainer has created a new file, but it is unclear if that list is related or designed to replace the original<sup>[[2]](https://github.com/blogmangit/Cosmetic-Filters/commits/main/adguard_cb_user_filter_1667069852317.txt)</sup>. It is also small and rarely updated.
I can readd it with the new name, but for now I have just deleted it.

Remove blogmangit Cosmetic-Filters

---

services/Directory/FilterLists.Directory.Infrastructure.Migrations/Migrations/20230825224322_3805.Designer.cs
services/Directory/FilterLists.Directory.Infrastructure.Migrations/Migrations/20230825224322_3805.cs
services/Directory/data/FilterList.json
services/Directory/data/FilterListLanguage.json
services/Directory/data/FilterListSyntax.json
services/Directory/data/FilterListTag.json
services/Directory/data/FilterListViewUrl.json

Remove OwlStudio ABP Rules, as it seems to no longer exist.

Remove OwlStudio ABP Rules

---

services/Directory/data/FilterList.json
services/Directory/data/FilterListLanguage.json
services/Directory/data/FilterListMaintainer.json
services/Directory/data/FilterListSyntax.json
services/Directory/data/FilterListTag.json
services/Directory/data/FilterListViewUrl.json
services/Directory/data/Maintainer.json
services/Directory/data/lint.sh

Adds [Microsoft GitHub Less Social](https://codeberg.org/toastal/github-less-social) uBlock Origin rules.
[^1]
[^1]: Please consider [giving up MS GitHub](https://sfconservancy.org/GiveUpGitHub/) or offering a non-proprietary, non-US-corporate-controlled mirror for this free software project. I wish to delete this Microsoft account in the future, but I need more projects like this to support alternative methods to send patches & contribute.

add github-less-social uBO

---

.github/workflows/web.yml

Potential fix for [https://github.com/collinbarrett/FilterLists/security/code-scanning/2](https://github.com/collinbarrett/FilterLists/security/code-scanning/2)
To fix the issue, we need to add a `permissions` block to the `build_and_deploy_staging` job. This block should specify the minimal permissions required for the job to function correctly. Based on the workflow's actions, the job likely only needs `contents: read` permissions to access repository contents and `id-token: write` permissions for authentication purposes.
The `permissions` block should be added directly under the job definition (`build_and_deploy_staging`) to ensure it applies only to this job and does not affect other jobs in the workflow.
---
_Suggested fixes powered by Copilot Autofix. Review carefully before …

Potential fix for code scanning alert no. 2: Workflow does not contain permissions

---

.github/workflows/web.yml

Potential fix for [https://github.com/collinbarrett/FilterLists/security/code-scanning/4](https://github.com/collinbarrett/FilterLists/security/code-scanning/4)
To fix the issue, we need to add a `permissions` block to the `build_and_deploy_production` job. Based on the actions performed in this job, the minimal required permissions are `contents: read` and `id-token: write`. The `contents: read` permission is needed for accessing the repository's contents, and the `id-token: write` permission is required for authentication with Azure Static Web Apps.
The `permissions` block should be added immediately after the `runs-on` key in the `build_and_deploy_production` job.
---
_Suggested fixes powered by Copilot Autofix. Review carefully before merging._

Potential fix for code scanning alert no. 4: Workflow does not contain permissions

---

.github/workflows/directory.yml

Potential fix for [https://github.com/collinbarrett/FilterLists/security/code-scanning/6](https://github.com/collinbarrett/FilterLists/security/code-scanning/6)
To fix the issue, we will add a `permissions` block to the `deploy` job. This block will explicitly define the minimal permissions required for the job to function. Based on the job's functionality, it likely requires `contents: read` to access the repository's contents and `packages: read` to pull the Docker image from the container registry. No write permissions are necessary for this job.
---
_Suggested fixes powered by Copilot Autofix. Review carefully before merging._

Potential fix for code scanning alert no. 6: Workflow does not contain permissions
